// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnyJJKatnD8CYBnRKjEe6CBDyBdJIuNfU',
    appId: '1:712910935337:web:6d5e4e1401b63b3fdbd338',
    messagingSenderId: '712910935337',
    projectId: 'note-app-fb421',
    authDomain: 'note-app-fb421.firebaseapp.com',
    storageBucket: 'note-app-fb421.appspot.com',
    measurementId: 'G-695FE90YBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnA6C_nL-hZurx09jybvU6403U3-fDanU',
    appId: '1:712910935337:android:8aeebe1f0a169139dbd338',
    messagingSenderId: '712910935337',
    projectId: 'note-app-fb421',
    storageBucket: 'note-app-fb421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYJfapRjrvMqnzNEddeCXouM__MfdCgUg',
    appId: '1:712910935337:ios:6242d812f1f029a7dbd338',
    messagingSenderId: '712910935337',
    projectId: 'note-app-fb421',
    storageBucket: 'note-app-fb421.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYJfapRjrvMqnzNEddeCXouM__MfdCgUg',
    appId: '1:712910935337:ios:70c5f334eebfaec0dbd338',
    messagingSenderId: '712910935337',
    projectId: 'note-app-fb421',
    storageBucket: 'note-app-fb421.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
